<a href="https://colab.research.google.com/github/sheraz658/PIAIC_AI_Q2/blob/main/NumpyAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  

In [ ]:
nullVector = np.zeros(10)

In [ ]:
nullVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
secondVector = np.arange(10,50)

In [ ]:
secondVector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.shape(secondVector)

(40,)

In [ ]:
secondVector.dtype

dtype('int64')

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>

In [ ]:
np.show_config

<function numpy.__config__.show>

In [ ]:
secondVector.ndim

1


In [ ]:
boolArray = np.array([1,1,1,1], dtype=bool)

In [ ]:
boolArray

array([ True,  True,  True,  True])

In [ ]:
twoDArray = np.array([[1,2,3], [4,5,6]])

In [ ]:
twoDArray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
threeDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
threeDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])